
sudu: required

language: generic

services:
  - docker

before_script:
  - echo "start creating an image with docker"
  - docker build -t app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true app-test npm run test -- --coverage
#Dockerreactapp-env.eba-jf8xeiip.ap-northeast-2.elasticbeanstalk.com
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: "Dockerreactapp-env"
  bucket: "elasticbeanstalk-ap-northeast-2-368004543901"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SCRET_ACCESS_KEY
