
sudu: required

language: generic

services:
  - docker

before_script:
  - echo "start creating an image with docker"
  - docker build -t app-test -f Dockerfile.dev .

script:
  - docker run -e CI-true app-test npm run test -- --coverage

after_success:
  - echo "Test Success"